name 'uniak-networkdevice'
version '0.0.1'

author 'Markus Burger <markus.burger@uni-ak.ac.at>'
license 'Apache'
project_page ''
source ''
summary 'network device extensions for cisco'
description ''
dependency 'puppetlabs/stdlib', '>=4.1.0'
dependency 'example42/icinga', '>=2.0.10'
